# -*- coding: utf-8 -*-
"""Epic_Games

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElwJZThk3g6t5ZjWovWycRiGxgfzwcc6
"""

# pip install legendary-gl

import subprocess
import json
import requests
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


# --- USER CONFIGURATION (EDIT THIS) ---
EMAIL_SENDER = os.environ.get("EMAIL_SENDER")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD")  # Google App Password, not main password
EMAIL_RECEIVER = "work.halal.zobaer@gmail.com"

def get_free_games_from_store():
    """Fetches currently free games from Epic's public API."""
    url = "https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions"
    try:
        data = requests.get(url).json()
        games = data['data']['Catalog']['searchStore']['elements']
        free_games = []

        for game in games:
            # Logic to find 0-cost promotions
            promotions = game.get('promotions')
            if not promotions: continue

            # Check both promotionalOffers and upcomingPromotionalOffers (we only want active ones)
            active_promos = promotions.get('promotionalOffers')
            if not active_promos or not active_promos[0]['promotionalOffers']: continue

            for offer in active_promos[0]['promotionalOffers']:
                if offer['discountSetting']['discountPercentage'] == 0:
                    # Construct the store URL
                    slug = game.get('productSlug') or game.get('urlSlug')
                    store_url = f"https://store.epicgames.com/en-US/p/{slug}"

                    free_games.append({
                        'title': game['title'],
                        'url': store_url
                    })
        return free_games
    except Exception as e:
        print(f"❌ Error fetching store data: {e}")
        return []

def get_my_library():
    """Uses Legendary to get a list of games you already own."""
    try:
        # Check if legendary is installed and authenticated
        result = subprocess.run(
            ['legendary', 'list-games', '--json'],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            print("⚠️ Legendary CLI returned an error. Are you authenticated?")
            return []

        library = json.loads(result.stdout)
        # Return a set of titles for faster lookup
        return {g['app_title'] for g in library}
    except FileNotFoundError:
        print("❌ 'legendary' command not found. Run: pip install legendary-gl")
        return []

def send_email(games_to_claim):
    """Sends an HTML email with direct claim links."""
    if not games_to_claim: return

    print(f"📧 Sending email for {len(games_to_claim)} games...")

    # Create valid HTML table rows
    rows = ""
    for game in games_to_claim:
        rows += f"""
        <tr>
            <td style="padding: 10px; border-bottom: 1px solid #ddd;">
                <strong style="font-size: 16px;">{game['title']}</strong>
            </td>
            <td style="padding: 10px; border-bottom: 1px solid #ddd; text-align: center;">
                <a href="{game['url']}"
                   style="background-color: #007bff; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px; font-weight: bold;">
                   GET IT NOW
                </a>
            </td>
        </tr>
        """

    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
            <div style="background-color: #333; color: white; padding: 20px; text-align: center;">
                <h2 style="margin:0;">🚀 Free Games Alert</h2>
            </div>
            <div style="padding: 20px;">
                <p>The following games are <strong>FREE</strong> right now and missing from your library:</p>
                <table style="width: 100%; border-collapse: collapse;">
                    {rows}
                </table>
                <p style="margin-top: 20px; font-size: 12px; color: #666;">
                    Click the button to open the Epic Store page and claim it manually.
                </p>
            </div>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = EMAIL_SENDER
    msg['To'] = EMAIL_RECEIVER
    msg['Subject'] = f"CLAIM NOW: {len(games_to_claim)} New Free Games Found!"
    msg.attach(MIMEText(html_content, 'html'))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(EMAIL_SENDER, EMAIL_PASSWORD)
            server.send_message(msg)
        print("✅ Email sent successfully!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    print("--- 🎮 Epic Games Checker Started ---")

    # 1. Get Lists
    free_games = get_free_games_from_store()
    owned_games = get_my_library()

    print(f"Found {len(free_games)} free games on store.")
    print(f"Found {len(owned_games)} games in your library.")

    # 2. Filter Logic
    claimable_games = []
    for game in free_games:
        # Simple string matching (Case insensitive for safety)
        if game['title'] not in owned_games:
            claimable_games.append(game)
            print(f"  [NEW] Found claimable game: {game['title']}")
        else:
            print(f"  [OWNED] You already have: {game['title']}")

    # 3. Action
    if claimable_games:
        send_email(claimable_games)
    else:
        print("✅ No new games to claim. You are up to date.")

        
import subprocess
import json
import requests
import os

# --- CONFIGURATION ---
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")

def get_free_games():
    """ Fetches currently free games from Epic."""
    url = "https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions"
    try:
        data = requests.get(url).json()
        games = data['data']['Catalog']['searchStore']['elements']
        free_games = []

        for game in games:
            promotions = game.get('promotions')
            if not promotions: continue
            active = promotions.get('promotionalOffers')
            if not active or not active[0]['promotionalOffers']: continue
            
            for offer in active[0]['promotionalOffers']:
                if offer['discountSetting']['discountPercentage'] == 0:
                    slug = game.get('productSlug') or game.get('urlSlug')
                    free_games.append({
                        'title': game['title'],
                        'url': f"https://store.epicgames.com/en-US/p/{slug}"
                    })
        return free_games
    except:
        return []

def get_my_library():
    """ Checks what you own using Legendary."""
    try:
        result = subprocess.run(['legendary', 'list-games', '--json'], capture_output=True, text=True)
        if result.returncode != 0: return []
        return {g['app_title'] for g in json.loads(result.stdout)}
    except:
        return set()

def send_telegram_msg(message, buttons=None):
    """Sends a message to your Telegram."""
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message,
        "parse_mode": "Markdown"
    }
    if buttons:
        payload["reply_markup"] = json.dumps({"inline_keyboard": buttons})
        
    requests.post(url, json=payload)

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    if not TELEGRAM_TOKEN or not TELEGRAM_CHAT_ID:
        print("❌ Error: Missing Telegram secrets.")
        exit(1)

    print("--- 🎮 Epic Agent (Telegram) ---")
    
    free_games = get_free_games()
    owned_games = get_my_library()
    
    # Check for new games
    new_games = [g for g in free_games if g['title'] not in owned_games]

    if new_games:
        print(f"Found {len(new_games)} new games.")
        
        # Build the message
        msg = f"🚀 *New Free Games Detected!*\n"
        buttons = []
        
        for game in new_games:
            msg += f"\n• {game['title']}"
            # Add a button for each game
            buttons.append([{"text": f"Get {game['title']}", "url": game['url']}])
            
        msg += "\n\nClick the buttons below to claim them!"
        send_telegram_msg(msg, buttons)
        
    else:
        # Simple status update
        print("All clear.")
        msg = f"✅ *Daily Check Complete*\nNo new games. You own all {len(owned_games)} games currently in your library."
        send_telegram_msg(msg)

